### PR TITLE
Do redirect if slug is changed (with settings)

### PR DESCRIPTION
**Pull request by remik**

### CODE REVIEW

**Comment by remik** [comment]
Some builds are freezing (on test: pages.tests.test_selenium.SeleniumTestCase.test_admin_move_page when trying to save screenshot - do you need it? I would save it only with some flag or environment settings). The same is on master.

**Comment by batiste** [comment]
@remik I don't particularly need the screenshot no. Only for debugging. Good if you can enable it with a setting variable :+1:

**Comment by remik** [comment]
Done in #126.
Will update this one after other one as there can be git conflict in doc.

**Comment by remik** [comment]
Updated. Please check.

**Comment by batiste** [comment]
I am actually surprised your code works this way. I was expecting you will be using the PageAlias model

https://github.com/batiste/django-page-cms/blob/master/pages/models.py#L521

I am unsure what is the best way and I need to think about it a little bit more. Have you though about the performances implications of your approach?

**Comment by batiste** [comment]
I didn't remembered how the page resolution worked. This is obviously a smart way to implement it. I just hope this doesn't trigger too many extra SQL queries.

**Pull request merged**
