### PR TITLE
Grappelli support

### PR DESCRIPTION
**Pull request by remik**
Basic Grappelli support. There might be some glitches but overall it looks good.

This is small change for CSS and JS but double check would be nice. Thanks.

### CODE REVIEW

**Comment by batiste** [comment]
Cool I am happy you have time to work on the CMS.

I tested the PR but I couldn't see any changes? Is this merely about getting the compatibility going?

**Comment by remik** [comment]
You need to:
 - install `pip install django-grappelli` (make sure you have Django 1.9 or you will need install older version)
 - uncomment in `settings.py` and `urls.py`

**Comment by remik** [comment]
Also make sure I didn't break clean Django - I tested but you know double check is better.

**Comment by batiste** [comment]
Sorry but I think my latest change created a conflict. Could you fix that and will merge just right after.

**Comment by batiste** [comment]
I merged with master. It seems to look fine for most of the things but the drag and drop dialog in the page list is unusable (css issue)

**Comment by remik** [comment]
Thanks. I will create issue for it and fix soon.

**Pull request merged**
